# Docker Compose file for Flutr
#
# Install Docker on your system to run and test
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
# Start database: docker compose up db
# Run migrations: docker compose run migrate
#       Stop all: docker compose down (add -v to wipe db)
#

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: info
  
services:
  objectstore:
    image: hb-objectstore:latest
    container_name: hb-objectstore
    build:
      context: ./hb-objectstore
    environment:
      DATABASE_HOST: postgres 
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      <<: *shared_environment
    ports:
      - '55001:55001'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["--app_env", "development", "--hostname", "0.0.0.0"]
    networks:
      flutr:


networks:
  flutr:
    name: flutr
    external: true
